# [Kubernetes Orchestration]
# minikube start --nodes=2
# kubectl apply -f davinci-deployment.yaml
# minikube service davinci-service

apiVersion: apps/v1
kind: Deployment
metadata:
  name: davinci-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: davinci
  template:
    metadata:
      labels:
        app: davinci
    spec:
      containers:
      - name: davinci
        image: bdostumski/davinci:1.0.0
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: davinci-service
spec:
  type: NodePort
  selector:
    app: davinci
  ports:
  - port: 8080
    targetPort: 80

